name: CI

on:
  push:
    branches: ["development"]         # run on every commit in dev
  pull_request:
    branches: ["master","development"]              # run full suite on PRs to master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download ReviveMe-API.jar
        run: |
          mkdir -p lib
          curl -L \
            -o lib/ReviveMe-API.jar \
            https://github.com/FavioMc19/ReviveMe-API/releases/download/1.0.0/ReviveMe-API.jar

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build (no tests on dev pushes)
        if: github.event_name == 'push'
        run: ./gradlew clean build -x test

      - name: Build and Test (full on PRs)
        if: github.event_name == 'pull_request'
        run: ./gradlew clean build
